# Generated by Django 4.1.7 on 2023-03-16 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0002_personnel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="id",
            field=models.PositiveIntegerField(
                editable=False,
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MaxValueValidator(13)],
            ),
        ),
    ]
