# Generated by Django 4.1.7 on 2023-03-16 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0004_alter_personnel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="id",
            field=models.PositiveIntegerField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MaxValueValidator(9999999999999)],
            ),
        ),
    ]
