# Generated by Django 4.1.7 on 2023-05-24 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0045_auto_20230524_0841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 24, 19, 9, 12, 715576)
            ),
        ),
    ]
